#!/usr/bin/env bash
# This script displays the time for 12 hours and 59 minutes in the required format.

hour=0

while [ "$hour" -le 12 ]; do
  echo "Hour: $hour"
  
  minute=1
  while [ "$minute" -le 59 ]; do
    echo "$minute"
    minute=$((minute + 1))  # Increment minute
  done

  hour=$((hour + 1))  # Increment hour
done
